### ISSUE TITLE
Git Cloning ended with Error

### ISSUE THREAD

**Issue by bean19** [Mrbrutal/Traincraft-164#2]
The Cloning ended with Error:

No submodule mapping found in .gitmodules for path 'Resources'

**Comment by Hanse00** [comment]
It does appear to me like the "Resources" location in the repository doesn't actually link to anywhere. Is that an error, or am I missing something?

**Comment by lehjr** [comment]
It probably points to a location that is inaccessible, like the private repo on Bitbucket

**Comment by Mrbrutal** [comment]
I'll add the assets to the github later today, for now you can use the ones from the latest download on www.traincraft-mod.com.
